name: simple_notepad
description: A new Flutter project.
publish_to: 'none'

version: 0.1.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  handy_window: ^0.3.1
  printing: ^5.11.0
  shared_preferences: ^2.2.0
  yaru: ^0.9.0
  yaru_icons: ^1.0.4
  yaru_widgets: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets: []

