name: simple-notepad
version: 0.1.2
summary: Simple notepad
description: A simple notepad app

confinement: strict
base: core18
grade: stable

architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

apps:
  simple-notepad:
    command: simple-notepad
    extensions: [flutter-stable]
    slots:
      - dbus-simple-notepad
    plugs:
      - home
      - removable-media

parts:
  simple-notepad:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration


slots:
  dbus-simple-notepad:
    interface: dbus
    bus: session
    name: com.example.simple_notepad
